aipVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-daos
  spec:
   accessModes:
     - ReadWriteOnce
   resources:
      requests:
      storage: 10Gi
   storeageClassName: standard-rwo
  
---
aipVersion: apps/vi
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: msql
    spec:
       containers:
       - image: /Documentos/Aulas/Kubernetes/Dio_Kubernetes/k8s-projeto1-app-base-main /projeto-database:1.0
         args:
         - "--ignore-db-dir=lost+found"
         imagePullPolicy: Always
         name: mysql
         ports:
         - containerPort: 3306
           name: mysql

         volumeMounts:
         - name: msql-dados
           mountPath: /var/lib/mysql/
       volumes:
         - name: mysql-dados
           persistentVolumeClaim:
             claimName: msql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
  spec:
  containers:
  - name: php
    image: /Documentos/Aulas/Kubernetes/Dio_Kubernetes/k8s-projeto1-app-base-main /projeto-backend:1.0
    imagePullPolicy: Always
    ports:
    - containerPort: 80